### ISSUE TITLE
Automatic trailer from the information area

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#554] opened 2024-03-10 00:14 UTC
### Skin section

Video Info Dialog

### Feature description

It would be really nice if the trailer launched automatically from the information area, from the "Play" and/or "trailer" button. And it stops automatically, as soon as you change tabs, or you leave the information area. 

### Why is this feature needed? Please justify and explain.

This would solve the usability problem that makes it difficult to stop the trailer. In addition, this would remain in the logic of "tabs" which display the information on the page without needing to press it.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2024-03-10 02:49
Duplicate of #141

**Closed by jurialmunkey** 2024-03-10 02:49 UTC
Labels: enhancement

**Comment by Bindou01** [comment] 2024-03-10 08:11
So, if the trailer launches automatically on the wallpaper, could pressing the "trailer" button launch the trailer in full screen mode?
