### ISSUE TITLE
[BUG] Clearlogos

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#154] opened 2023-10-11 05:36 UTC
### Skin section

Library Views

### Current Behavior

I am not sure if this is a skin issue or maybe TMDB Helper issue.

I have seen a few posts on github about clearlogos not showing.

I have 2 setups and a lot of clearlogos do not show up on AF. Sometimes they will show up in a widget but not in titles and vice versa. Though when you go to the context menu - TMDB Helper - Manager Artwork. It shows the clearlogos. Sometimes it will refresh the clearlogo. Other times it wont.

I have the service monitor and widget settings active in TMDB Hepler aswell.

I have also testing it by going back to AH2 and they show up on there perfect fine.
![noclearlogo](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/589d5818-e9ba-4759-a6f1-295a3d6351c3)

### Expected Behavior

For clearlogos to show up as intended

### Steps To Reproduce

Go to your local library (I am using TMDB Helper to get trakt list to library) as this is where a lot of clearlogos are not loading. 

### Screenshots and Additional Info

![noclearlogo](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/55dd947e-277e-40b6-ba2a-1a3a2277d866)
![fanartsettings](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/f8d971bc-1bb4-4f08-8c01-f5d01d1c1fd8)
![clearlogo](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/d3c62aa9-a82d-4dec-9d58-bcf9e9294cc4)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by RentreX** [comment] 2023-10-11 08:58
I have done a bit more test on a fresh install.

When using AH2 there is no issues at all from what I can see.

AF though still have a lot of issues. Sometimes the clearlogo will show for about 1 second and then revert to text.

Also using a widget with treading today (TMDB helper) has some clear logos missing. So it isn't just a library issue. 

For example Ahsoka is not showing clearlogo. I would pretty much guarantee that Ashoka would have a clearlogo.

![20231011_185413](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/bb088fb1-cf5a-48a3-8757-1251e8482b49)

**Comment by jurialmunkey** [comment] 2023-10-11 10:38
The difference between the two skins is that AF *only* uses cropped logos where AH2 will fallback to the uncropped logo if the cropped one is unavailable -- so that explains the different behaviour you're seeing.

There are other problems with the approach used in AH2 which is why I don't use it in AF. The more important question, though, is why TMDbHelper is not providing a cropped logo considering there is a clearlogo available.

Is there any particular pattern you're seeing? 

Also do you have a log? Might give some clues.

**Comment by RentreX** [comment] 2023-10-11 10:45
Oh that makes a lot of sense.

That I have not been able to figure out as if yet.

I am not able to get the logs at this point in time but I will upload them when I can. Is there settings you need me to turn on? Like in TMDB helper etc?

**Comment by RentreX** [comment] 2023-10-11 12:54
Also in regards to any patterns. Not that I can see.  

Some load perfectly fine.

Some load for a second and then revert to text.

Some load when going to manage art and picking the clearlogo again.

Some don't load at all no matter what I do.

I am using a windows 11 PC and a ccwgtv. Both have the issue. Though from a quick glance it looked as if some where the same on both devices and some where different.

Are all the cropped clear logos stored in the crop_v2 of TMDB helper?

**Comment by jurialmunkey** [comment] 2023-10-11 14:09
These errors are the reason:

```
Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/7/7ba8e575.png'
```

TMDbHelper is trying to read the local clearlogo files from your Kodi thumbnail cache but it can't. If it can't read the file then it can't crop it.

As to why it can't read it, I'm not sure. Either the file doesn't actually exist at all, which indicates a problem with your Kodi thumbnail cache (maybe you deleted files without clearing the Kodi thumbnail db) -- OR the file does exist but has some type of permissions lock on it which prevents it from being read.

**Comment by RentreX** [comment] 2023-10-11 14:15
Thanks for the quick response.

That is a possibility due to having to test the path subs etc.

Would this also be the issue for why the Ahsoka in trending widget is not showing? I do not have it in my library at all.

**Comment by woodside007** [comment] 2023-10-11 15:17
Just chiming in here to say I have the same problem. I've unchecked "Prefer artwork from TMDb first if available" in TMDBhelper API settings and it helped a lot but still come across one that will not load the clearlogo until I load the choose art dialog in info window and then immediately back out of it. It then shows the clearlogo. Unchecking that setting I listed above has helped tremendously but still come across one that won't show once in a while.

**Comment by RentreX** [comment] 2023-10-12 01:32
I did another clean install (using path subs and env.properties again) and only installed the jurialmunkey repo addons. 

connected trakt to tmdb helper
selected the lists
added to library from tmdb helper
scanned with TMDB TV scraper.

it again has some of the same errors though others work perfectly fine. Could this be a issue with it thinking that some of the thumbnails are in special://profile/thumnails and not looking at the path sub in advancedsettings.xml?

https://paste.kodi.tv/owefesexuc.kodi

On a side note. Before doing a clean install I tried using the TVDB scraper instead. When using TVDB most of if not all the clearlogos work. (though i do not like the fanart with text so I would perfer not to use it)

**Comment by RentreX** [comment] 2023-10-12 01:34
It's exactly the same shows from what I can see.

![20231012_113339.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/003dfe8b-70c8-4075-8bd2-1289791597f5)

![20231012_113305.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/ff008dd0-1ae3-4266-8d30-3931f5fe9415)

![20231012_113313.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/693af8e1-d495-49f6-a3f4-fb4994b9ff11)

**Comment by RentreX** [comment] 2023-10-12 03:38
On line 337 of the log it says 

> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/5/56500410.png'

The thumbnail is in:

> /storage/80F3-170F/Android/data/org.xbmc.kodi/files/thumbnails/5/

all folders in /sdcard/kodi_data/.kodi/userdata/Thumbnails/ are empty as the path substitution has put them into the new directory. This was set up before adding anything to the library. So it isn't due to deleted files without clearing the Kodi thumbnail db. 

It is strange that most work perfectly but a few throw an error because it is looking in the wrong spot. 

![clearlogo](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/9a661218-33b0-48b9-8b31-fa136a9ac527)

**Comment by RentreX** [comment] 2023-10-12 04:09
I have just check my recent kodi log.

every error is for items appearing in the trending tmdb helper widget. I have looked at every png file that it says it can not find and not one of them is from my library files. 

For the ones that the error is for I did see that the first time I scrolled through the widget those shows did not appear. But scrolling through them twice fixed the issue of them not showing except for one (American Horror Stories). I have this in my library and it is the only one that will not apply the clearlogo when scrolling through more than once. 

Though there is no error in the log that shows any of the ones in my library. Except for American Horror Stories though the clearlogo is shown in the thumbnail folder.

**Comment by RentreX** [comment] 2023-10-12 04:35
This is the new kodi log: https://paste.kodi.tv/ivinetuxug.kodi

Not in Library:

Stargate SG-1
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/3/30609aac.png'

South Park (Shows in Trending Widget)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/0/0a94f0c4.png'

Supernatural (Shows in Trending Widget)
>  Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/c/ca339640.png'

The Wheel of Time (Shows in Trending Widget)
>  Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/7/71e1774c.png'

Mission Impossible: Dead Reckoning Part One (Shows in Trending Widget)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/d/df0270b7.png'

Game of Thrones (Shows in Trending Widget)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/8/853ea8ba.png'

Loki (Shows in Trending Widget)
>  Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/1/1004da32.png'


In Library:

American Horror Stories (DOES NOT show in Trending Widget or in Library)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/9/9478d84d.png'

> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/9/9478d84d.png'

> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/9/9478d84d.png'

> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/9/9478d84d.png'

The Boys (DOIES NOT show up in Library & isn't in trending widget so I can not see if it is working or not)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/3/38e6e227.png'

Teenage Mutant Ninja Turtles: Mutant Mayhem (Shows in Trending Widget & in Library)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/3/39fef6a4.png'

Harry Potter and the Philosophers Stone (Shows in Trending Widget & in Library)
> Image error: Could not open cached image --> [Errno 2] No such file or directory: '/sdcard/kodi_data/.kodi/userdata/Thumbnails/b/b9b26128.png'

That is all the errors I could see in the log though there is a lot of TV shows in the library that don't show a clearlogo and there isn't an error in the log for them.(movies don't seem to really have the issue)

**Comment by RentreX** [comment] 2023-10-12 04:48
When scraped with TMDB TV scraper

![20231012_144312.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/f7120ce2-9e95-41a3-a321-6becbb5c2c8e)


When scraped with TVDB V4 scraper

![20231012_144603.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/39e2ca8b-1769-4f1a-b18e-b5922736002c)



As you can see that the missing clearlogos show up when using TVDB V4 but not with TMDB TV scraper.

When switching back to TMDB TV scraper the clearlogo disappears again.

**Comment by RentreX** [comment] 2023-10-12 05:07
I have just had a chance to look at the PC  logs. (Everything else above was from the ccwgtv)

There is no ERRNO errors in the logs though tv shows still have missing clearlogos when using TMDB TV scraper.

Some of the TV shows on the PC show the clearlogo where they are missing on the ccwgtv.

**Comment by RentreX** [comment] 2023-10-12 05:24
@jurialmunkey I think I figured out the reasoning.

When I went into the crop_v2 folder there is a lot of temp_cropped-******.png files. If I remove the temp_ from the name then the clearlogos appear.


![cropped](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/6ed526e2-038c-4b74-aab1-9d3f350dc593)
![tempcropped](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/1ee41818-e976-42e0-ad26-f6b2c4c5afc1)
![20231012_152223](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/154a66c6-5a01-4ec1-a07a-919615962cc3)

**Comment by jurialmunkey** [comment] 2023-10-12 06:36
This sounds like a file permissions issue

Since you're on Android make sure you've done the steps here under Android users heading
https://kodi.tv/article/kodi-nexus-rc-2/

**Comment by RentreX** [comment] 2023-10-12 07:09
I had to have that setting enabled to be able to access folders. So that setting has been enabled since the start.

If it was a file permissions issue wouldn't that mean that none of the clearlogos would work? Some clearlogo go from temp_cropped to cropped perfectly. Others get stuck on temp_cropped.

Plus it also happens on PC aswell. As you can see from the attached photo.

![20231012_170752.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/f91d2cf4-d8cd-4654-bef4-cd3eb2fc87eb)

It's able to access the folder and files to be able to add the temp_cropped file but then it can't access it to rename to cropped on both windows and android.

**Comment by jurialmunkey** [comment] 2023-10-12 09:34
The temp file is written using Kodi's internal file operation module xbmcvfs, and so that write operation will have the same permissions as any other internal operation.

The python pillow module is then used to load the image from the temp file into memory, perform the image manipulations, and the save back to disk to the correct filename. Finally, the image is closed and the temp file is deleted. There is no renaming of files.

The error message in the log is from pillow attempting to load the image. It only attempts to load images that xbmcvfs reports as existing. So there is a permissions mismatch here where xbmcvfs thinks a file exists (can read) but pillow does not (can't read).

I'll add some extra logging and we can see the exact message.

**Comment by RentreX** [comment] 2023-10-12 09:39
That makes sense.

I have tried on another PC (windows 11) and the same thing is happening from a clean install that has never had kodi installed.

I can fully understand that android 11 and above has had a rework that makes it very hard to access files. Though I would not think that it would be a issue on windows. 

I'm more than happy to get to the bottom of it with the extra logging when available

**Comment by jurialmunkey** [comment] 2023-10-12 09:51
Yeah should be fine on Windows (it's what I use Kodi on and I don't have this issue). I suspect it's to do with the path substitutions since xbmcvfs and pillow will be accessing the file system in different ways.

Can you install this version of TMDbHelper:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/testing_croplog.zip

Then turn on debug logging and restart Kodi.

It's going to spew a lot of log spam but will indicate for each item whether Kodi is reporting the crop logo to already exist, or if TMDbHelper is reporting that it completed a new crop, or if the pillow module raised an exception whilst writing.

It will also write out the filename, destination and temp target (if making a new crop) which might give some further clues.

**Comment by RentreX** [comment] 2023-10-12 10:13
https://paste.kodi.tv/ewozowimap.kodi

there is a few crop errors

**Comment by RentreX** [comment] 2023-10-12 10:34
https://paste.kodi.tv/apuzocurur.kodi (windows 11)

It has crop errors aswell

**Comment by RentreX** [comment] 2023-10-12 10:42
I had to have that setting enabled to be able to access folders. So that setting has been enabled since the start.

If it was a file permissions issue wouldn't that mean that none of the clearlogos would work? Some clearlogo go from temp_cropped to cropped perfectly. Others get stuck on temp_cropped.

Plus it also happens on PC aswell. As you can see from the attached photo.

![20231012_170752.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/f91d2cf4-d8cd-4654-bef4-cd3eb2fc87eb)

It's able to access the folder and files to be able to add the temp_cropped file but then it can't access it to rename to cropped on both windows and android.

**Comment by RentreX** [comment] 2023-10-12 10:43
By the looks of it is:

> L to RGBa not supported

**Comment by jurialmunkey** [comment] 2023-10-12 11:41
Thanks this is really useful. That'd definitely be the cause for some of them and would line up with what @woodside007 mentioned about about disabling "Prefer artwork from TMDb first if available" as I've noticed some logos on TMDb being SVG or having weird colour profiles whereas fanart.tv is much stricter about their requirements.

It looks like there's still some other issues on Android with permissions but I'll see if I can deal with this colour profile conversion issue first.

**Comment by RentreX** [comment] 2023-10-12 11:57
There is also one in each device that states:

> image file is truncated

But most of them are L to RGBa

**Comment by jurialmunkey** [comment] 2023-10-12 12:06
The `image file is truncated` error is usually due to very large image sizes.
I was able to reproduce the L to RGBa error and should be able to work around it.

**Comment by RentreX** [comment] 2023-10-12 12:35
Not a problem at all. Glad to be able to help somehow.

Oh okay.

Yeah I'm not exactly sure what is going on with android at all. Though I'm hopeful with the conversion issue fix that it will solve 99% of it.

**Comment by RentreX** [comment] 2023-10-12 12:48
I have also just seen in the android log 
for a few of them up near the start to middle of the log.

> 'NoneType' object has no attribute 'replace' 

Is this a android permission issue? As there isn't any in the windows 11 log that I could see.

**Comment by jurialmunkey** [comment] 2023-10-12 13:33
The fix for L to RGBa is in version 5.1.42 of TMDbHelper. Give it a try and let me know how it goes.

The NoneType error isn't important. It only happens because there's no clearlogo listed for that item to crop and I'm being particularly verbose with the logging. Normally it would simply be caught and ignored.

The ones that might be related to file permissions are the "could not open cached image" errors. I'm not really sure what the deal is there, but it seems to be only on Android and I don't have any Android devices so I can't reproduce it myself.

**Comment by RentreX** [comment] 2023-10-12 13:52
I have just tested it and can confirm that it is working as intended.

Oh okay. No worries.

The  "could not open cached image"  errors are odd. As they shouldn't be going to the folder that it says they are. Path Sub changes that. Plus that is only for when it is in focus for the first time in a widget. If you go to the next item and then back to it the clearlogo would always be there. Except for on the very rare TV show cases. 

Though it all seems to be good now. Even in the widgets.

**Comment by RentreX** [comment] 2023-10-12 14:04
Might have found another issue with clearlogos. I didn't see this before now.

When a widget item doesn't have a clearlogo to begin with and it crops it. Some times it will not show the correct clearlogo until you go to the next item and then back to it.

Also some times it doesn't load any clearlogo until you go to the next item and then back.

Other times it refreshes and loads it without having to go to the next item and back.

Examples below:

Example 1: Totally Killer loaded Guardians of the Galaxy. Going to the next item in widget and then back got it to load the correct clearlogo.

Example 2: The walking dead Daryl Dixon did not load any clearlogo. Going to the next item in widget and then back got it to load the clearlogo.


![20231012_235936](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/ad0a0236-e7f9-471d-92fd-4176490c0be5)
![20231013_000005](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/8d932a5e-6330-474f-9b43-7e9c278dcd2a)
![20231012_235500](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/80fba0a6-1d74-45b1-9810-e3d44a4a88b4)
![20231012_235510](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/8fedd824-405c-47a1-98e2-6840e4c1743d)

**Comment by jurialmunkey** [comment] 2023-10-13 02:22
> When a widget item doesn't have a clearlogo to begin with and it crops it. Some times it will not show the correct clearlogo until you go to the next item and then back to it.
> Also some times it doesn't load any clearlogo until you go to the next item and then back.

There's a couple of different reasons this occurs.

(1) If the image has not yet been cached and processed by Kodi (or is otherwise unavailable) then Kodi will continue to display the previous image in the texture control until Kodi has loaded+processed+cached the new image.

Also there is sometimes a race between the disk updating its listings after a file write and the metadata property being set which points to the file. If the property points to a file that doesn't exist then Kodi will blank the texture control. 

For (1) there's no solution. It's simply a matter of Kodi can't display a texture until it is processed+cached.

For (2) there is a solution (sit in a loop checking the disk and not progressing file write is confirmed) but it's a waste of resources, will make retrieving other details delayed/slower, and potentially could cause other issues (get stuck until timeout because something happened in the middle of a write like disk corruption or reload skin etc.). 

For what is a minor display issue that only occurs on first process of the image it's simply not worth adding the complexity to try to "fix" it and probably will just open a can of worms in terms of knock-on issues. 

It's really not much different from when you do a fresh install of Kodi and you get blank textures for a while until all the library images have been properly processed and cached. After a bit of usage has built up a decent cache of images, you really don't see this type of thing that much.

**Comment by RentreX** [comment] 2023-10-13 02:38
Yeah that is fully understandable. It isn't much of an issue for me but I thought I would bring it up incase you were not aware.

**Comment by jurialmunkey** [comment] 2023-10-13 03:53
I'm going to close this issue as I think probably have solved as much as I can considering I don't have any android devices to investigate the read issue -- but do let me know if you notice other similar issues.

At least now with the read issue, the fallback to downloading the source from online will work. Before the problem was that reading the cache was failing and then converting the online version to RGBa was also failing so we didn't get any image. Whereas now we get an image, it's just a bit slower first time because we can't read Kodi's precached version.

**Closed by jurialmunkey** 2023-10-13 03:53 UTC
Labels: bug

**Comment by RentreX** [comment] 2023-10-16 13:43
Still no issues at all. I think you have completely fix it 👌

**Comment by GalacticWave** [comment] 2024-05-07 03:42
@jurialmunkey - Sorry for commenting on this old closed issue thread as I wasn't sure whether to create a new ticket or not because the issue I am facing is similar to this. My primary question is whether SMB protocol is supported by TMDBH. 
I already moved the userdata thumbnails folder to the netowrk storage and I see Kodi is working fine.  But when I use the cache image location for TMDBH, I get the following error: 

`debug <general>: [plugin.video.themoviedb.helper] Image error: Could not get image for https://image.tmdb.org/t/p/original/fsh0CquP8MudNlr46fm8dKnNMPy.png (try 1) -> [Errno 22] Invalid argument: 'smb://nas540/Kodi/Cache/TMDB_Images/crop_v2/temp_cropped-c9fb71885b560776fe002b99e17f42f1.png'`

So, as mentioned above, the temp file is getting created but I guess the pillow module is not able to read the SMB protocol as its throwing invalid argument error. If it is that SMB is not supported, can it be updated to support that? If not, then what would be the possible other options to have the cache folder on a NAS drive? 

Thanks!
