### ISSUE TITLE
🌟 Option to minimize or switch off menu button

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#584] opened 2024-03-13 18:11 UTC
### Skin section

Widgets

### Feature description

When using top bar, the menu button is still visible on the side despite the rest of the top bar buttons being minimized... Could we please get the ability to minimize it as well.

### Why is this feature needed? Please justify and explain.

When using warp on content end, you're unable to reach the button at all, the long press back button does the job but the menu button still stays on the side despite being unusable.

### Screenshots and Additional Info

![Screenshot_20240313_180155_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/3cd93235-c268-411f-abd6-70a2448257ea)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Rinicko** [comment] 2024-03-14 05:09
I saw a request similar to this one that had already been answered and closed... wondering if this request is different as It's not about the dimensions or the whole left side but just the menu button 🤔

**Comment by jurialmunkey** [comment] 2024-03-14 06:17
Yep this is definitely a different request.

The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.

I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others.

**Comment by adamosborne83** [comment] 2024-03-14 06:53
> Yep this is definitely a different request.
> 
> The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.
> 
> I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others. 

I'm guessing he just wants a clear front screen, I ALMOST requested the same thing, and even took one of my famous videos to show, but, even though I use the 1 menu, it just needs 'something'
https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d1059f81-5540-407b-bea5-9ef5a919c436

**Comment by Rinicko** [comment] 2024-03-14 10:11
> Yep this is definitely a different request.
> 
> The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.
> 
> I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others.

Ahh, nice nice... thanks for your reply.  I understand that due to it being on the other hubs and other pages, it may look inconsistent...  But maybe it'll be good for users who don't need it to be able to switch it off on the homepage, I've seen someone else also talk about it on the forum.

**Comment by Rinicko** [comment] 2024-03-14 10:14
> > Yep this is definitely a different request.
> > The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.
> > I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others.
> 
> I'm guessing he just wants a clear front screen, I ALMOST requested the same thing, and even took one of my famous videos to show, but, even though I use the 1 menu, it just needs 'something' https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d1059f81-5540-407b-bea5-9ef5a919c436

Yes, that's exactly what I'm after.  How were you able to change it in that video?

**Comment by adamosborne83** [comment] 2024-03-14 10:18
> > > Yep this is definitely a different request.
> > > The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.
> > > I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others.
> > 
> > I'm guessing he just wants a clear front screen, I ALMOST requested the same thing, and even took one of my famous videos to show, but, even though I use the 1 menu, it just needs 'something' https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d1059f81-5540-407b-bea5-9ef5a919c436
> 
> Yes, that's exactly what I'm after.  How were you able to change it in that video?

If you follow the video, it shows you the settings I had to accommodate it.
😀

**Comment by Rinicko** [comment] 2024-03-14 10:26
> > > > Yep this is definitely a different request.
> > > > The problem with the other one was that they were complaining about the extra space in the margin, which is basically asking me to redesign the whole skin! This request is definitely not that.
> > > > I'll still have to think about it though as it is a fairly critical component for a lot of other areas of the skin and it is a bit weird to remove it only in one spot and not others.
> > > 
> > > 
> > > I'm guessing he just wants a clear front screen, I ALMOST requested the same thing, and even took one of my famous videos to show, but, even though I use the 1 menu, it just needs 'something' https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d1059f81-5540-407b-bea5-9ef5a919c436
> > 
> > 
> > Yes, that's exactly what I'm after.  How were you able to change it in that video?
> 
> If you follow the video, it shows you the settings I had to accommodate it. 😀

Ohh I see... that option gets rid of the full screen though, and the linked visibility feature. Thanks anyway 👍

**Comment by Bindou01** [comment] 2024-03-19 14:11
@jurialmunkey 
Hi Jurial, an idea :
1. Leave the search icon visible as you did within reach, because it is very useful, and your new search system is so ergonomic that you want to use it all the time. I adore !
2. Remove the menu icon, and replace it with a “return” click to bring up the pane and/or, a left click when you are on the “search” icon.

**Comment by Bindou01** [comment] 2024-03-19 14:41
> > @jurialmunkey Hi Jurial, an idea :
> > 
> > 1. Leave the search icon visible as you did within reach, because it is very useful, and your new search system is so ergonomic that you want to use it all the time. I adore !
> > 2. Remove the menu icon, and replace it with a “return” click to bring up the pane, and/or a left click when you are on the “search” icon.
> 
> The search page is window(1105), this means it can be positioned in a plethora of places on the skin, you can even map it to a button on your remote as I did or put it in your shutdown menu

Thanks for the tip Rinicko,
1. I prefer to have the search icon always available. This is more intuitive for casual users.
2. I find it more aesthetically coherent to always have at least one icon in this area, because this is the case everywhere else, and without that, it looks very empty!
3. My proposal is mainly based on ergonomics. This would make accessing the pane easier, it avoids having to look for the "Menu" icon, because sometimes pressing return takes you directly to it, sometimes not, and you need an additional click on menu to make the pane appear. With what I'm proposing, you can do it very quickly, just a few clicks on return without thinking, and the pane would appear which would be more practical in my opinion, and could allow you to remove the "menu" icon.

**Comment by xyzfre** [comment] 2024-03-19 16:28
I really think the way he has it now is just about perfect with the menu icon, and the search icon exactly where they're at

**Comment by Bindou01** [comment] 2024-03-19 16:33
My proposal does not necessarily require the removal of the menu button.  The two can coexist if desired.  I think that being able to bring up the pane by pressing return (without changing the Hub) would make navigation much more ergonomic.

**Comment by Rinicko** [comment] 2024-03-19 16:34
> I really think the way he has it now is just about perfect with the menu icon, and the search icon exactly where they're at

The problem is when using warp you can't really access it. I prefer warp when scrolling back and forth on widgets, it feels more intuitive and contained... So my proposal is just a way to minimize it or allow some users who also use warp to disable it, to achieve fullscreen on their homepage.

**Comment by Bindou01** [comment] 2024-03-19 16:37
I don't think it's incompatible.  Simply bring up the pane with the return key, only when we are at the start of the list of horizontal categories.  (not from widgets)

**Comment by Rinicko** [comment] 2024-03-19 16:42
> I don't think it's incompatible. Simply bring up the pane with the return key, only when we are at the start of the list of horizontal categories. (not from widgets)

It doesn't work, the return key takes it to the top bar

**Comment by Bindou01** [comment] 2024-03-19 17:04
No, it is not yet integrated, this is precisely the meaning of my proposal addressed to Jurial. ^^

**Comment by jurialmunkey** [comment] 2024-03-19 23:03
You are misunderstanding the point here @Bindou01

The setup being used here has the menu already at the top. There is no reason to expand the menu on left side because the menu is already at the top. This is an entirely different layout to what you are using.

**Comment by Bindou01** [comment] 2024-03-20 00:27
In fact, excuse me, I didn't read it correctly. (I cleaned)

**Comment by jurialmunkey** [comment] 2024-03-31 09:05
Resolved via customisation in https://github.com/jurialmunkey/skin.arctic.fuse/commit/afb4e4e407c14874767186f9b7dbe458e79ca4a6 for #666

**Closed by jurialmunkey** 2024-03-31 09:05 UTC
Labels: enhancement
