### ISSUE TITLE
Widgets not populating and causing system to time out or crash

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#105] opened 2023-08-17 14:25 UTC
### Skin section

Library Views

### Current Behavior

First of all I'm hoping im pointing to the right part of the skin in suggesting the bug occurs in the library view.  

Im finding that when widgets need to populate especially trailers once they have played it can take upward of 2 to 3 mins for the boxes to repopulate the widgets or most of the time the whole thing will crash back to desktop. 

If it does populate the trailer will work just fine but once the trailer has played the widgets all go blank then the spinning icon just spins for a good while before populating again or crashing to desktop, home screen.

### Expected Behavior

Repopulate of widgets within seconds or not even to go blank to Repopulate i think?

This is happening on the sheild and I don't use a pc for this skin so not sure how it plays out on pc.

### Steps To Reproduce

Go to information, trailer, play trailer, trailers will try to populate in widgets while trailer is playing,  when the trailer finishes all widgets will go blank  again and spinning wheel will now show widgets trying to populate for about 2 to 3 mins.

Im my case I was using Spider man accross the spider verse as there are multiple short trailers. See image's for an idea.
![20230817_145123](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/432d2cc4-b451-466f-9f22-d7090c20186c)

![20230817_145140](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/48664ef0-2742-4b39-8a13-31ae3104b3ae)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-08-18 10:51
I can't stop the reloading -- Kodi forces all containers to refresh whenever video playback stops.

It definitely shouldn't take several minutes to reload the same list though. Do you have a debug log of this happening? Might gives some clues as to what is actually going on.

**Comment by DROIDshield** [comment] 2023-08-18 11:46
Okay,  I'm working at the moment but will try and get you a log when I get home... cheers.

**Comment by DROIDshield** [comment] 2023-08-19 01:08
@jurialmunkey 
[kodi.log test video and trailer waiting for container to repopulate..txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/12384663/kodi.log.test.video.and.trailer.waiting.for.container.to.repopulate.txt)
[kodi.log startup.txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/12384664/kodi.log.startup.txt)
[kodi.log System sitting idel after container repopulate then Kodi crash back to desktop..txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/12384665/kodi.log.System.sitting.idel.after.container.repopulate.then.Kodi.crash.back.to.desktop.txt)
 Have a look at these files... im hoping these are the ones you are referring too. They show startup, run video then get trailers and to the point of kodi crash to desktop.

If these are not the files you refer to, let me know where to find what you need. Cheers.

**Comment by jurialmunkey** [comment] 2023-08-19 02:00
```
2023-08-19 00:54:22.526 T:21106   error <general>: Unable to find plugin plugin.video.themoviedb.helper

Error Contents: Unknown addon id 'plugin.video.themoviedb.helper'.

RuntimeError: Unknown addon id 'plugin.video.themoviedb.helper'.
```

These are very unusual errors that appear several times throughout your logs.

`2023-08-19 00:54:02.465 T:21080    info <general>: CAddonMgr::FindAddon: plugin.video.themoviedb.helper v5.1.34~nexus installed`

It looks like Kodi updated the plugin pretty much at startup, which ended up causing all those errors. A lot of important startup routines seem to have failed -- e.g. Trakt auth and the service monitor:

```
TraktCheckingAuth Timeout!

2023-08-19 00:54:01.260 T:21080   error <general>: CPythonInvoker(3, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.themoviedb.helper/resources/service.py): script didn't stop in 5 seconds - let's kill it
```

I'm hoping it's very much just a case of "have you tried turning it off and on again?". Try restart Kodi and see if you still get issues.

Addons which run services (e.g. TMDbHelper) really need a "restart after updates" option to start fresh but there's not really a way to force that in Kodi -- lately I've been pushing more frequent updates to TMDbHelper, so that might explain why you've seen this issue a few times.

**Comment by DROIDshield** [comment] 2023-08-19 06:23
Yeah I restart when updates are pushed... trakt seems to be working fine...I have full VIP package .. and that scrobbles fine.

If I switch the skin to AH2 no issues that works with any problems... switch back to fuse and it runs fir a bit then crashes... Will look at it more again after work and see what else I might find.

**Comment by jurialmunkey** [comment] 2023-08-19 07:41
> Yeah I restart when updates are pushed

Can you get me a log from after a restart. Those logs you uploaded before were from when there was an during the skin running -- so it's hard to separate the errors caused by that and other errors.

**Comment by DROIDshield** [comment] 2023-08-20 03:43
I've got the files here, I have to say, i rolled back TMDB helper to 4.10.14 from your version selection and it all ran smoothly. Of course it didn't have all of the containers etc as it an older version... then updabacknto the latest seems to have made it more stable but the glitching and crashing is there but not as heavy as was...  see what the files say to you. Cheers. 
[kodi.log  STARTUP.txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/12387184/kodi.log.STARTUP.txt)
[kodi.log Run trailers sytem lockup and crash after widgets populate..txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/12387185/kodi.log.Run.trailers.sytem.lockup.and.crash.after.widgets.populate.txt)
[kodi.log ROLLED BACK ADDON TO 4.10.14 NO ERRORS SYSTEN ITS THIME.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/12387186/kodi.log.ROLLED.BACK.ADDON.TO.4.10.14.NO.ERRORS.SYSTEN.ITS.THIME.log)

**Comment by jurialmunkey** [comment] 2023-08-20 06:29
You're getting a lot of item details database errors -- not sure if its the cause but definitely want to clear those up

Close Kodi, delete the item details cache file, and then restart Kodi
`kodi/addon_data/plugin.video.themoviedb.helper/plugin.video.themoviedb.helper/database_v6/ItemBuilder.db`

A setting which can help with that type of error is caching to memory because it reduces the amount of disk reads:
`TMDbHelper Settings > Expert > Cache disk reads to memory`

Also try adjusting max concurrent threads from unlimited to about 30. 
`TMDbHelper Settings > Expert > Max concurrent threads`

**Comment by DROIDshield** [comment] 2023-08-20 13:26
Soon as I get home, I'll be on it... HGV trucking takes up alot of my day... so will look at it this evening...many thanks...

**Comment by bassemhelal18** [comment] 2023-08-20 18:56
I got the same error script shortcuts submenu 2 and Kodi crash ![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/77381611/b58789d4-e166-491b-8f76-cc9677a8f79a)

**Comment by jurialmunkey** [comment] 2023-08-21 02:32
> I got the same error script shortcuts submenu 2 and Kodi crash

This "error" is not relevant. It will not cause a crash.

Please only provide full logs -- not screenshots or snippets. You can upload them by changing the fileextension to `.txt` or you can use https://paste.kodi.tv/

A log error is almost *never* the cause of a crash -- If Kodi has crashed it cannot write to the log anymore. So the log will only contain things which did *not* crash Kodi.

The reason I ask for full logs is because I need to see configuration details about the system setup. The log can also sometimes be useful for seeing a pattern of unusual or unexpected behaviour. A snippet of text tells me nothing relevant.

**Comment by jurialmunkey** [comment] 2023-08-21 02:54
> Soon as I get home, I'll be on it... HGV trucking takes up alot of my day... so will look at it this evening...many thanks...

No worries! No rush at all - whenever you get a chance.

I've pushed an update to TMDbHelper to force the mem caching setting to be always on for item details -- so that should help with the read/write errors at least. 

I really should've had it like that from the beginning since that particular DB has such high read/write traffic -- whereas the other DBs have less frequent concurrent access so are fine with it off to save some memory.

**Comment by DROIDshield** [comment] 2023-08-22 20:34
@jurialmunkey I've made the changes and I have to say, YES...... it's working beautifully so far. I've deleted the cache witch took age's but I we are good. Gonna tackle the art work next because I've notici can't change any posters or fanart.. things sir are looking great. Thank you for your work... star player...

**Comment by jurialmunkey** [comment] 2023-08-23 01:58
@DROIDshield - Great to hear! I'll close this for now but let me know if it starts happening again.

Also for the threads it's basically a case of finding the sweet spot between stability and performance -- you can definitely try pushing it higher and see what you can get away with, then drop it back down a step if/once you see issues.

**Closed by jurialmunkey** 2023-08-23 01:58 UTC
Labels: bug
