### ISSUE TITLE
Spotlight slide focuses on submenu not on categories

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.fuse#832] opened 2024-04-29 11:55 UTC
### Skin section

Widgets

### Current Behavior

When using the feature spotlight slide scrolling down, focuses on sub menu would be better if you can focus on categories ,not sure if this is intentional.

### Expected Behavior

When using the feature spotlight slide scrolling down, should focus on categories first.

### Steps To Reproduce

//

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment] 2024-04-29 11:56
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/2baa6ba6-d5a7-4526-9714-4bf518a72e17

**Comment by jurialmunkey** [comment] 2024-04-30 00:16
Yes this is intentional.

You and @adamosborne83 can duke it out over how it should behave. Winner takes all.

Closing as not a bug.

**Closed by jurialmunkey** 2024-04-30 00:16 UTC
Labels: bug
