### ISSUE TITLE
[BUG] More Information Crashes Kodi

### ISSUE THREAD

**Issue by Demonseed-jpg** [jurialmunkey/skin.arctic.fuse#129] opened 2023-09-16 01:00 UTC
### Skin section

Home Widgets

### Current Behavior

Opening any movie or show’s “Information” screen through TMDBHelper or the Home Screen crashes Kodi.

### Expected Behavior

The expected behavior is that the information screen pops up as expected.

### Steps To Reproduce

1. Click on any movie or show while the Kodi setting “Default select action” is set to “Show Information”.
2. Kodi crashes to Desktop.

### Screenshots and Additional Info

OS: SteamOS Holo 3.4.10
Build: 20230831.1

This problem does not exist when using Arctic Horizon 2. This issue has always existed for me while using this skin.

I can try to provide any information you need from my system. I am recently returning to Kodi after a long hiatus and also very very new to Linux (Steam Deck). Logs are planned when I figure out how to get those on Linux.

I am a huge fan of your skins and very excited to get this skin working. Thanks for all that you do!

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Demonseed-jpg** [comment] 2023-09-17 18:34
I have attached a Kodi log file to this comment. Please let me know if there’s anything else you need!
[kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/12643465/kodi.log)

**Comment by Demonseed-jpg** [comment] 2023-09-17 22:02
Update: I tested this skin on my Windows 10 PC and didn’t experience this problem. 

I haven’t seen a whole of issues brought up related to crashing on Linux, other than one other issue where you mentioned an issue with Python 3.10 which my Steam Deck was running. 

I upgraded it to 3.11.3 and am still experiencing this issue. Not sure if any of this helps anything but wanted to make sure you knew.

**Comment by Demonseed-jpg** [comment] 2023-09-26 20:14
Hi, just wanted to ping this again and see if there’s anything I can provide or help with to figure this out. I know you’re super busy so I really appreciate you reading this message.

**Comment by jurialmunkey** [comment] 2023-09-27 01:34
```
gdb not installed, can't get stack trace.

```

Really need a stack trace to be able to diagnose an application crash. Log by itself only really tells me what didn't cause the crash (if Kodi can write the log then it hasn't crashed yet).

Not too familiar with Steam Deck so I'm not sure exactly how you would go about installing gdb on it.

**Comment by Demonseed-jpg** [comment] 2023-09-27 17:23
Thanks for the tip on gdb. I’ll look into that one and come back with a stack trace log. I have very little experience in Linux, so apologies on not already having it.

**Comment by Demonseed-jpg** [comment] 2023-09-30 07:43
Still looking into this. So far I’ve found that Steam Deck’s OS is Arch Linux + KDE with an immutable file system. It seems I do have GDP installed, but because Kodi is running via Flatpak, I _think_ that might be why it thinks it isn’t. 

Sorry for the delay, getting the stack trace has proven to be a struggle lol.

**Comment by Demonseed-jpg** [comment] 2023-10-01 23:39
Update: I have found a way to run the Flatpak Kodi through gdb. While running, the terminal spits this out: https://pastebin.com/EXx1DX69
I’m not sure if that’s what you need, but it doesn’t feel like it.

I also a core dump file:
- core.kodi\x2ebin.[bunch of numbers].zst

I feel like this one does have the information you need, but I haven’t figured out how to read it yet. Is this file something you can work with? Or does it need to be in a user friendly format like the usual Kodi logs?

**Comment by jurialmunkey** [comment] 2023-10-04 03:53
> Update: I have found a way to run the Flatpak Kodi through gdb. While running, the terminal spits this out: https://pastebin.com/Z3dK10QJ

Yeah this is *almost* what I need, but it needs to be the output from gdb *inside* Kodi

You can see in that output 
```
Thread 1 "kodi.bin" received signal SIGSEGV, Segmentation fault.
```

Which is what we already know -- the OS told the Kodi application (kodi.bin) to exit forcibly as a safety precaution because the application accessed memory in an unexpected way (segmentation fault).

What we want to see is what thread *inside* Kodi had the segfault because that will give us an indication of whether it is actually Kodi itself or some addon that it is running in a subinterpreter inside the Kodi app (which is how all addons run).


What does Kodi log itself say? Is it still complaining about GDP not being installed?

**Comment by Demonseed-jpg** [comment] 2023-10-05 03:04
Well, that’s a start! I’ll keep doing research and playing with it till I get you whatever you need.

it no longer complains about gdb not being installed, however, it now just says this with nothing between it:
`##### STACK TRACE #####`
`##### END STACK TRACE #####`

**Comment by Demonseed-jpg** [comment] 2023-10-05 04:05
Alright, I’m my previous log, I wasn’t able to run `bt` after Kodi crashed due to it exiting for some reason. Now I was able to do that after Kodi crashed without exiting gdb. I’m not sure if this helps or if this is considered gdb inside of Kodi or not, but here it is:
https://pastebin.com/3ZyH6YWU

As for Jodi’s log now just skipping the Stack Trace section, I’m not sure why it’s doing that. I may have to raise a ticket with Kodi on Flathub and see if they can help.

**Comment by jurialmunkey** [comment] 2023-10-18 08:24
@Demonseed-jpg - Thanks that's great. Looking at the output, I think it is the same issue as in this one:
https://github.com/jurialmunkey/skin.arctic.fuse/issues/17#issuecomment-1767916832

I'm running LibreELEC in virtual machine and can reproduce the crash.

For videoinfo, I seem to be able to prevent it by removing this line
https://github.com/jurialmunkey/skin.arctic.fuse/blob/d18f593699067dd33668e976c50a9646c6179266/1080i/Includes_DialogInfo.xml#L1046

And possibly also this one (but seems to be really only that one above)
https://github.com/jurialmunkey/skin.arctic.fuse/blob/d18f593699067dd33668e976c50a9646c6179266/1080i/Includes_DialogInfo.xml#L1055


Looks like there's some issue on the *ELECs with scale aspectratio for textures in the info dialogs.

**Comment by jurialmunkey** [comment] 2023-10-18 08:25
Are you able to test commenting those out, then reload, and see if you still have the issue

**Comment by jurialmunkey** [comment] 2023-10-19 04:54
@Demonseed-jpg - Are you able to test version 0.3.4? Fairly sure this issue is the same as #17 and if it is, then it should be fixed now.

**Comment by Demonseed-jpg** [comment] 2023-10-19 05:11
Just updated it and works like a charm! Awesome to see you knock out two birds with one stone. 

I’ll read through the other post to understand what the problem was.

**Comment by jurialmunkey** [comment] 2023-10-19 05:29
It's a problem with nested includes.

Basically in the skin engine you can define an include like so:
```xml
<include name="MyInclude">
  <control type="group">
     <description>First Block of Code</description>
     <nested />
     <description>Last Block of Code</description>
  </control>
</include>
```

And then that allows you to include that code content whilst also sandwiching additional code in-between where the `<nested /> tag is placed: e.g.
```xml
<include content="MyInclude">
   <description>Middle Block of Code</description>
</include>
```

Generates:
```xml
  <control type="group">
     <description>First Block of Code</description>
     <description>Middle Block of Code</description>
     <description>Last Block of Code</description>
  </control>
```

The problem is that if you don't wrap the nested tag inside a group in the include definition then LibreELEC freaks out and segfaults. 

For example, you'd expect the following to be a different way of generating the same code but instead it crashes *ELECs

```
<!-- Definition -->
<include name="MyInclude">
     <description>First Block of Code</description>
     <nested />
     <description>Last Block of Code</description>
</include>

<!-- Usage -->
<control type="group">
  <include content="MyInclude">
   <description>Middle Block of Code</description>
  </include>
</control>

<!-- Generates -->
  <control type="group">
     <description>First Block of Code</description>
     <description>Middle Block of Code</description>
     <description>Last Block of Code</description>
  </control>
```

**Closed** 2023-10-19 06:18 UTC
Labels: bug

**Comment by Demonseed-jpg** [comment] 2023-10-21 18:06
Interesting, that makes sense. Thanks for the detailed explanation!

I saw on the other ticket that you’re gonna recreate it using Estuary and submit a ticket as the skin shouldn’t be able to crash Kodi. 

Since I’m using SteamOS with Kodi via Flatpak, should I also duplicate that ticket whenever you finish it for them as well, or do you think your ticket with them will eventually trickle down to Flatpak? (Or maybe they use the same version?)

**Comment by jurialmunkey** [comment] 2023-10-21 23:20
I would expect that any fix would probably work for all the linux based distributions.

I think the code in kodi is the issue - there's some fault in the logic of nested includes because they have a couple of quirks like this where things that you would expect to work dont. It just happens that the windows equivalent of that library manages to avoid a segfault, but it is likely still encountering an error there - it's just not critical on Windows.
