### ISSUE TITLE
:bug: footer play count issue?

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#506] opened 2024-02-18 16:37 UTC
### Skin section

Widgets

### Current Behavior

Hello,

I just noticed in the footer it has a play count. As you can see I have played every episode but 1 and the play count remains at 0. Does this only work with library content?

Kind regards
SJ

### Expected Behavior

Correct display count however I'm not sure if it's just for library content.

### Steps To Reproduce

1. View a show via a widget populated by a add-on.

### Screenshots and Additional Info

![20240218_163146](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/c895c70b-8a7b-43d6-adfc-3ccc966e10ac)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2024-02-18 23:14
Duplicate of #502

Update the skin. Should already be fixed.

**Closed by jurialmunkey** 2024-02-18 23:14 UTC
Labels: bug

**Comment by SJ1O** [comment] 2024-03-10 13:31
Hey Jurial,

I just did the most recent update and it no longer shows the play count. It says (more unavailable) however if I enable hide peak widget it shows the play count again. But I do like to be able to see the widgets below but also like the play count on my final widgets. Just wondering if this is something that can be tweaked?

Cheers
Sam
