### ISSUE TITLE
Updates not working on kodi 20.2

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#275] opened 2023-12-08 13:06 UTC
### Skin section

Other

### Current Behavior

Hi Jurialmunkey 
Updates not showing up on kodi 20.2 after latest repository update.

### Expected Behavior

Updates working on kodi nexus

### Steps To Reproduce

Try to update skin or new installation on kodi 20 nexus

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment] 2023-12-08 13:14
You need to update kodi to nightlies or stay on repo 3.3

**Comment by jurialmunkey** [comment] 2023-12-08 13:50
> You need to update kodi to nightlies or stay on repo 3.3

Repo for Nexus is exactly the same in both 3.3 and 3.4 -- all the version change does is add an Omega branch. It doesn't change the Nexus one.

The issue is I accidentally copied the GUI bump into the nexus version of the skin. It will be fixed soon.

**Closed by jurialmunkey** 2023-12-08 13:50 UTC
Labels: bug

**Comment by rapteev** [comment] 2023-12-08 13:57
Thank you

**Comment by adamosborne83** [comment] 2023-12-08 13:59
I'll shut up in future haha
