### ISSUE TITLE
Classic mode navigation broken

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#800] opened 2024-04-26 05:00 UTC
### Skin section

Widgets

### Current Behavior

Since several last updates navigation in the main menu became worse every time. I suppose the author doesn't use classic mode with combined widgets to test it.
You just cannot get to first (three of four in my case) widget rows - skin doesn't let it. No matter vertical or horizontal layout.

### Expected Behavior

Working navigation.

### Steps To Reproduce

Use classic mode with combined widgets. Try to use widgets on the main page.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2024-04-26 09:27
I do use classic mode... It is the only mode I use on my loungeroom setup.

I cannot reproduce this issue. Classic mode works fine for me both with and without combined enabled.

**Comment by patkino** [comment] 2024-04-26 09:43
There are several people at forum, who also experience this issue and one of them uploaded video

**Comment by jurialmunkey** [comment] 2024-04-26 09:49
I'm not doubting it happens, I just cannot reproduce it myself. Need more information about how to make it happen.

**Comment by KenshiroBlind** [comment] 2024-04-26 14:40
The way i can reproduce the is usually by watching a tv show/movies be it streaming it or from my local library and once the movie finishes/ the tv shows episode ends, i press the back/return button on my remote to go back to the main menu and  then if i try to scroll down to the tv shows/movies widgets on my local library, 3 times out of 5, navigation just get stuck on the home /default widget.
same thing happens when i live stream a tv channel ..after a while (20+minutes)
![WhatsApp Image 2024-04-17 at 2 30 12 PM](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162586511/037f0dc6-01d9-4770-bd13-a2ab2c34281e)

ps:i attached an old screen shot of my layout which i've been using for a while now, hope that help

**Comment by loddie88** [comment] 2024-04-26 15:57
Based off mine (I am the person who filmed the video) and others experiences, I think the problem is limited to the combined mode only.  This also started for me very recently, so I'm assuming its associated with a recent update.

**Comment by scoobyd00** [comment] 2024-04-26 20:00
Have the same issue. After watching a program and returning I can't then scroll right off the side widgets. I've got movies, tv shows, music on my side bar
I can scroll right on movies and music but not on TV shows

**Comment by jurialmunkey** [comment] 2024-04-28 15:17
Should be largely fixed in v0.6.31

**Closed by jurialmunkey** 2024-04-28 15:17 UTC
Labels: bug

**Comment by patkino** [comment] 2024-04-28 19:06
Now the navigate through widgets option is gone 🤦‍♂️

**Comment by jurialmunkey** [comment] 2024-04-28 23:18
. 
Jesus christ... No thanks for spending more than 14 hours over my weekend fixing this.... Just passive aggressive entitled comments treating me like a company selling a product rather than one guy giving up practically all his free time to share his hobby for free. 

Combined is not compatible with this option  without creating bugs. It will not return. It was never the intent of the option to be for combined and only worked by accident in that mode as a side effect of the hack used. It doesn't even make sense since there is no hint that pressing down will offer more content.

**Comment by patkino** [comment] 2024-04-29 04:00
Thanks, really
Sorry for criticism
