### ISSUE TITLE
Info Screen, Premiered Date

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#1019] opened 2024-07-25 20:37 UTC
### Skin section

Widgets

### Current Behavior

It will not showthe numeric date

### Expected Behavior

To show 1st 2nd 3rd etc

### Steps To Reproduce

Go into a movie with Show Info amd will not show the actual date

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment] 2024-07-25 21:10
It should currently have the long date format (eg. Tuesday, 13 June 2023) along with the respective status in parentheses.

![image](https://github.com/user-attachments/assets/848a3512-a84e-41fd-9323-ffca2106cdfe)

What does it look like on your setup?

**Comment by adamosborne83** [comment] 2024-07-26 14:50
See videohttps://github.com/user-attachments/assets/441f7525-7616-4d28-a449-ae4ddad2b67b

**Comment by L0bsang** [comment] 2024-07-26 17:27
I can confirm I have seen this too for certain content; at the time I thought it was because there wasn't a valid date to pull for that specific media.

**Comment by jurialmunkey** [comment] 2024-07-27 01:16
Kodi issue with it supplying an invalid long date format string for your system. 

As you can see here in https://strftime.org/ the `%-d` is a platform specific string, but Kodi is hardcoding it as an assumption it works rather than actually querying the system C datetime module to see if it is supported on that platform ... as result instead you simply get `-d` rather than the day number because your system can't format it.

It needs to be fixed in Kodi so that Kodi supplies a valid date format string to Python scripts.

As a work around, you can try changing your long date format in Interface > Regional settings. 

You're looking for a date format that doesn't use single digits for days (if you look at the reference sheet you can see `%d` which outputs a leading zero like `08` is supported on all platforms, whereas the single digit `%-d` is platform specific). 

So something like DD instead of D 

i.e. In this screenshot, you should change to the highlighted one instead, not the ticked one (which is probably what you have selected at the moment)
![screenshot00620](https://github.com/user-attachments/assets/e12bf64f-9064-40fa-b05b-3c27149866b6)

**Comment by jurialmunkey** [comment] 2024-07-27 01:21
Relevant Kodi issue report here: https://github.com/xbmc/xbmc/issues/25066

**Comment by adamosborne83** [comment] 2024-07-27 07:06
> Relevant Kodi issue report here: https://github.com/xbmc/xbmc/issues/25066

Thank you as always J.

**Closed** 2024-07-27 07:06 UTC
Labels: bug, external issue

**Comment by L0bsang** [comment] 2024-07-27 21:24
Had to come back and look at this for the solution. Many thanks! Will have to remember to go change it on my devices.
