### ISSUE TITLE
:bug: Navigation Issue - Classic mode side Menu

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#550] opened 2024-03-09 09:01 UTC
### Skin section

Widgets

### Current Behavior

I have Arctic Fuse configured for Classic mode with the option "Content - Move between widget groups" disabled. I've noticed an issue after installing an update. I have also seen the issue after switching between Classic and Complex modes and back again.

The issue is that pressing right from the first side menu item does not navigate to the widgets. Pressing right from other side menu items works fine.

The issue is resolved by enabling the option "Content - Move between widget groups", and then navigating to the second side menu item's widget group. Then up to the first widget group. I can then disable this option and the fix persists , so is a useable workaround.

### Expected Behavior

Navigation should work as intended

### Steps To Reproduce

1. use classic mode
2. install update 
3. try to navigate from first side menu item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2024-03-09 09:50
Can you test with 0.5.04 and see if it is still a problem? I can't reproduce but I didn't recently fix a couple things related to the moving between groups in general.

One thing to check is that you've definitely got a widget in the first slot for the group with items available-- from a fresh start where there's no previous focus for the group, the skin will just try to focus the first ID in the group (and if that widget has no items then you get stuck).

Also good idea to restart Kodi if you're changing this option or between classic/complex to make sure Kodi clears all the home window properties properly -- when you reload a skin, Kodi only clears out properties for other windows, but not the home, so only way to get a proper fresh start without any previous layout settings persisting is a restart.

**Comment by berkhornet** [comment] 2024-03-09 10:54
Thanks for reply.

Checked a couple of things:

  *   I do have a widget with items available in the first slot for the widget group
  *   I've installed 0.5.04 and got the same problem, just using Classic (no switching between Classic and Complex)
  *   A Kodi re-start resolved the issue, and a cleaner workaround

I will continue to investigate further to try and isolate the cause.

Thanks again

**Comment by Ade-AV** [comment] 2024-03-11 08:33
I have the same issue on Apple TV

**Comment by L0bsang** [comment] 2024-03-11 09:20
I am also having this issue on an Nvidia shield. 

In classic mode with "Move between widget groups" unticked; pressing right from the first menu item does not move to the first widget, sometimes it works after a skin reload or kodi restart.

My first sidemenu item is "Home" with 2 widgets: a Custom Submenu of smart playlists and "Random Trending Combined" from TMDBHelper.

If it helps, I noticed I cannot delete that Home menu item (only allows rename and change of icon) but I can add another Home menu item that then has all the options.

**Comment by berkhornet** [comment] 2024-03-11 12:05
@jurialmunkey. So far I have been unable to reproduce this bug in a reliable manner. After installing the latest update everything worked fine, but the issue occurred again a few times later in the day. One thing I noticed was that when it happens the first widget for the first item is faded out. Will keep trying.

**Comment by jurialmunkey** [comment] 2024-03-12 00:47
I'm fairly sure it is related to the `Reload()` happening in the middle of the base properties being set. If you happen to be on another widget from another group when the skin reloads on the home screen then the wrong property gets set (the one you're on rather than the one Kodi will reset the position to).

I think the above commit should fix it but still need to test further to be sure.

**Comment by L0bsang** [comment] 2024-03-12 06:52
Seems to be fixed in v0.5.08. 
Pressing right on the first menu item goes onto the first widget in classic mode, even after a reload or a restart.

Many thanks!

**Comment by berkhornet** [comment] 2024-03-12 09:09
Many thanks. I will install and try out a few scenarios.

Mick Rollitt
________________________________

**Comment by jurialmunkey** [comment] 2024-03-12 09:18
>  I was too hasty to confirm, after tweaking my complex mode setup (where I had other issues with category visibility being shared for addon and home sidemenus) I switched back to classic mode and had a recurrence of this issue.

@L0bsang - Did you rebuild after making changes?

**Comment by L0bsang** [comment] 2024-03-13 00:14
@jurialmunkey - Indeed I did rebuild. 
But it is possible that the one time I noted the recurrence, it hadn't finished rebuilding, sometimes the skin-variables notification sticks at 50% for a few seconds.

Will monitor further and try various scenarios as well.

**Comment by jurialmunkey** [comment] 2024-03-29 09:22
I think this is now fixed.

**Closed by jurialmunkey** 2024-03-29 09:22 UTC
Labels: bug
