### ISSUE TITLE
:bug: classic mode navigation issues

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#826] opened 2024-04-28 13:31 UTC
### Skin section

Widgets

### Current Behavior

content>back parent is broken with latest update 0.6.30. pressing back from any widget always takes you to the first side menu item and not respective side menu item.

content>end is bumping and not wrapping anymore. was this navigation setting removed on latest version as I cannot find it anymore? even from first item of any widget, when pressing left, focus in moving to first side menu item and not wrapping to the end of the widget. 

I have the following navigation settings configured:

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/137268669/8ad79b96-2070-4bbe-8207-f5039620f336)

### Expected Behavior

content>back parent should take you respective side menu item as before.

option for content>end to wrap from first to last item of widget row.

### Steps To Reproduce

press back from any widget and focus will go to first side menu item.

press left from first widget and focus will go to first side menu item and not wrapping to last item of widget.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2024-04-28 13:56
Disable "Menu > Left = Options" and it will wrap.

**Comment by jurialmunkey** [comment] 2024-04-28 13:57
> content>back parent is broken with latest update 0.6.30. pressing back from any widget always takes you to the first side menu item and not respective side menu item.

Not broken, it is intentional. 

Classic mode now contains all widgets in a single grouplist.

Pressing back to go to the parent item takes you to the top of the grouplist. That is the first widget.

**Comment by vella9** [comment] 2024-04-28 14:13
> Disable "Menu > Left = Options" and it will wrap.

focus is still going to side menu before wrapping. not how it was before (from first to last item of widget row)

> If you want widgets to be broken into separate groups, then disable the option to move between groups.

I had this option enabled due to #673. Will test this again and let you know.

**Comment by jurialmunkey** [comment] 2024-04-28 15:12
> focus is still going to side menu before wrapping. not how it was before (from first to last item of widget row)

I needed to simplify these options.

If side menu is expanded, the left/right movement loops through the menu (and if menu set to open on left it stops at ends). 
If side menu is minimised, the content wraps (and up goes to the menu instead).

So if you want content to wrap, then minimise the menu.

> I had this option enabled due to https://github.com/jurialmunkey/skin.arctic.fuse/issues/673. Will test this again and let you know.

I think that issue should be *mostly* fixed now (hopefully). Next update will improve it further.

**Comment by vella9** [comment] 2024-04-29 05:52
> > focus is still going to side menu before wrapping. not how it was before (from first to last item of widget row)
> 
> I needed to simplify these options.
> 
> If side menu is expanded, the left/right movement loops through the menu (and if menu set to open on left it stops at ends). If side menu is minimised, the content wraps (and up goes to the menu instead).
> 
> So if you want content to wrap, then minimise the menu.

On a personal side of things, I prefer the menu expanded tbh, I think that this is the best view for classic mode (couldn't set it to open on left though, not sure how this is done).

Another personal preference is the way navigation was handled before these changes. I think that it looked and felt better/smoother. On the latest updates, to have the same behavior as before, I had to sacrifice 'the move between widgets' option and although it contains the sections much better, widget continuation between different sections is lost.

Then again, these are just my personal preferences and I don't want to intrude, as I do not know the what plans you have for this amazing skin. I appreciate your time and effort to accommodate us on a daily basis. Thank you.


> > I had this option enabled due to #673. Will test this again and let you know.
> 
> I think that issue should be _mostly_ fixed now (hopefully). Next update will improve it further.

I tested this a bit yesterday and it looks like it is fixed now, thank you for this, the only thing that I wanted to mention is that upon returning to the main screen, any button press will take you to the first side menu item. Other than that, the main issue seems fixed. Thanks once again.

**Comment by jurialmunkey** [comment] 2024-04-29 10:24
> On a personal side of things, I prefer the menu expanded tbh, I think that this is the best view for classic mode 

That's the same as what I use myself. But I find wrap to be confusing compared against looping. 

Can you explain a bit more how you use it with wrap enabled? Don't you find it confusing that pressing left at the start of the list doesn't go left to the menu and instead wraps around? 

Or is this with touch mode enabled to disable the screen peek? That's the only way I can wrap (excuse the pun) my head around it making any sort of sense to prefer wrap over loop with menu expanded.

I'm not opposed to wrap entirely, just want to remove some of the more micro type navigation settings to ensure there is a reliable pattern of navigation -- it gets a bit much trying to manage every possible permutation in every possible configuration and all that I end up doing is fixing one problem to cause another in an endless game of whack-a-mole.


> (couldn't set it to open on left though, not sure how this is done).

No, no, this is a misunderstanding. The setting toggles whether on left again *from* the menu will then open the options (power) dialog (or view filter in library, or discover filter in discover etc.) 

That's why it makes it also bump on the right -- since you can't continue left to loop around, the loop is also disabled on the right.

> Another personal preference is the way navigation was handled before these changes. I think that it looked and felt better/smoother.

It's less about preference and more about working within the technical limitations of the skin engine. Either the skin is a buggy mess where you can get trapped on the side menu and need to restart Kodi to regain control, or these sacrifices are made.

**Comment by vella9** [comment] 2024-04-29 17:37
@jurialmunkey would it make sense adding a 'Menu>Left' bump or null (does not loop) option? Not sure if the bump effect itself fits well though.

Just thinking out of the box, at least this way, it won't loop from widget first item to side menu and to widget last item upon presses. It would bump/null on menu left press. as for widget last item, it would need to bump onright as well.

Just a thought.

**Comment by vella9** [comment] 2024-04-29 18:23
@jurialmunkey would it make sense adding a 'Menu>Left' bump or null (does not loop) option? Not sure if the bump effect itself fits well enough.

Just thinking out loud here, at least this way, it won't loop from widget first item to side menu and to widget last item upon presses. It would bump/null on menu left press. as for widget last item, it would need to bump onright as well.

Just a thought is all.

**Comment by jurialmunkey** [comment] 2024-05-01 04:58
Managed to figure out a way for back to go to current group icon even if move between enabled https://github.com/jurialmunkey/skin.arctic.fuse/commit/ba3ef1432ae55ca4cdb97798eca8f60c8c2e8759

> Just thinking out loud here, at least this way, it won't loop from widget first item to side menu and to widget last item upon presses. It would bump/null on menu left press. as for widget last item, it would need to bump onright as well.

To me that sounds worse. 

IMHO bump on left would be the least expected behaviour. I'd expect it to either to wrap or go to the side.

A good middle ground might be to have onback=menu automatically wrap rows always (i.e. if onback=menu then widgets always behave as if the menu were minimised even if it isn't). 

I think wrapping lists is the only real reason to enable onback=menu anyway, so may as well bundle it.

That still cuts down on micro options. And more importantly, it prevents the user from locking themselves out from the menu -- which is good for me because it means less people complaining at me about their bad choices of settings making the skin not make sense.

**Comment by vella9** [comment] 2024-05-01 12:21
> Managed to figure out a way for back to go to current group icon even if move between enabled [ba3ef14](https://github.com/jurialmunkey/skin.arctic.fuse/commit/ba3ef1432ae55ca4cdb97798eca8f60c8c2e8759)

Awesome jurial, thank you. However, when setting onback=menu with move between enabled, it is not respecting the navigation as intended. It is defaulting to the last side menu item that had focus.

> A good middle ground might be to have onback=menu automatically wrap rows always (i.e. if onback=menu then widgets always behave as if the menu were minimised even if it isn't).
> 
> I think wrapping lists is the only real reason to enable onback=menu anyway, so may as well bundle it.

Great addition, thank you for this jurial 🙏 I owe you a coffee.

> because it means less people complaining at me about their bad choices of settings making the skin not make sense.

I'm sorry for the hassle that I might have caused. Definitely not my intention, I try to be as nonintrusive as possible, but still report any issues/bugs that I find for the benefit of this great skin. Thank you as always @jurialmunkey!

**Comment by jurialmunkey** [comment] 2024-05-01 23:14
No no hassle! Not directed at you. I have no problem people reporting bugs or making requests (as long as it is somewhat thought out and they aren't rude about it). 

I should be able to adjust menu onback to go to correct position - just an oversight.

**Comment by vella9** [comment] 2024-05-02 12:25
> I should be able to adjust menu onback to go to correct position - just an oversight

great, thank you @jurialmunkey!

**Comment by vella9** [comment] 2024-05-02 13:04
> when setting onback=menu with move between enabled, it is not respecting the navigation as intended.

I also noticed that this is also sometimes occurring when setting onback=parent with move between enabled.

**Comment by xyzfre** [comment] 2024-05-02 13:28
@vella9 where did you find the setting move between widgets. I tried looking for it, but I could not find it. I use complex mode.

**Comment by vella9** [comment] 2024-05-02 13:31
@xyzfre if I remember correctly this was removed for complex mode. Not sure though cause I use classic mode. For classic mode it is under Navigation.

**Closed** 2024-05-05 00:33 UTC
Labels: bug
