### ISSUE TITLE
[BUG] Widgets not keeping defined styles while using multiple Kodi profiles

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#100] opened 2023-08-15 08:02 UTC
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

I have noticed that if we define different widget styles for multiple Kodi profiles then while switching the profiles the styles are not maintained. They are getting switched to landscape. This is usually happening while using same type of widgets in 2 profiles with different labels. I'm not exactly sure what's causing this issue. Could you please check and advise?

### Expected Behavior

Widgets should maintain defined styles in different profiles and shouldn't switch to landscape.

### Steps To Reproduce

For example, create a widget in home/hub in profile 1 with a label. Create another widget in the same position on another profile with a different label. Give same/different styles to each of them, e.g. Card/Square to both. When you switch profiles one of them will not maintain the defined style and will switch to landscape. You have to then make the labels same for both the profile widgets and use same hub, only then they will follow the defined styles, but if you use the same labels then they will only take the same styles and can't use different styles with the same labels. So either you've to use same labels and same styles or different labels, different styles in different widget positions for multiple profiles.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-08-15 08:34
Is this only happening to the submenu widget which adapts to the selection?

Can you try reloading the skin using the `ReloadSkin()` command after switching profiles and see if that helps.

Sometimes kodi doesn't properly reload the skin after switching and so some of the settings persist from the previous profile (it's been a long standing kodi issue with profiles).

**Comment by AakashC2020** [comment] 2023-08-15 08:45
> Is this only happening to the submenu widget which adapts to the selection?
> 
> Can you try reloading the skin using the `ReloadSkin()` command after switching profiles and see if that helps.
> 
> Sometimes kodi doesn't properly reload the skin after switching and so some of the settings persist from the previous profile (it's been a long standing kodi issue with profiles).

I've explained the situation in details with an example above now. Please check that. ReloadSkin() is not helping. I've already checked that. Only if I disable and enable a widget in one profile then the skin shortcuts reload and the styles get corrected for that profile, but the other profile's style gets messed up. The only solution is as I've explained above now. Kindly check and advise. For now I've resolved the issue by using the same labels, same widget positions, and same hubs to use the same styles for the 2 profiles. Otherwise, I've to use different labels, different widget positions, and different hubs to use different widget styles for the 2 profiles. However, I'm not sure if this is a proper solution.

**Comment by jurialmunkey** [comment] 2023-08-15 10:06
This sounds like a skinshortcuts issue not building files correctly per profile. 

The problem is that skinshortcuts outputs its config to the skin folder. So if each profile is reusing the same addons then it will get the same config output file. 

Skinshortcuts tries to deal with this by building separate includes for each profile name - - so first thing to check is that your profiles have unique names so that there isn't a conflict on the check for which to include  

If they definitely all have unique names, then it's likely something that needs to be fixed in skinshortcuts itself rather than anything I can do in the skin - it sounds like the way it checks label ids is messed up. 

You could try setting up your profiles so that they have separate addons - possibly that might work because it will mean each profile has its own separate copy of the skin addon.

When I'm back home I'll see if I can recreate the issue and let you know if I see a different approach which might work

**Comment by AakashC2020** [comment] 2023-08-15 10:10
> This sounds like a skinshortcuts issue not building files correctly per profile.
> 
> The problem is that skinshortcuts outputs its config to the skin folder. So if each profile is reusing the same addons then it will get the same config output file.
> 
> Skinshortcuts tries to deal with this by building separate includes for each profile name - - so first thing to check is that your profiles have unique names so that there isn't a conflict on the check for which to include
> 
> If they definitely all have unique names, then it's likely something that needs to be fixed in skinshortcuts itself rather than anything I can do in the skin - it sounds like the way it checks label ids is messed up.
> 
> You could try setting up your profiles so that they have separate addons - possibly that might work because it will mean each profile has its own separate copy of the skin addon.
> 
> When I'm back home I'll see if I can recreate the issue and let you know if I see a different approach which might work

Fine @jurialmunkey. I will wait for your update and expert advise. For now I'm using the widgets in the way I've described above. Thank you!

**Comment by Omarscomin** [comment] 2023-08-26 22:16
Just wanted to chime in and say that this happened to me with Arctic Horizon 2 as well. The second profile that I added, in addition to the master, was a fresh set up with completely different add ons than my Arctic Horizon 2 profile. In fact, the profile wouldn't load from the log in screen _prior_ to me installing _any_ add ons onto said profile. 

I'm totally fine with it and it's not negatively affecting me what so ever. Just wanted to provide some more pieces to the puzzle :)

**Comment by jurialmunkey** [comment] 2023-11-20 11:06
@AakashC2020 - When you get a chance to test, can you let me know if this is still an issue in v0.4 ?

As far as I can tell from my testing, profile support is working correctly with the new script. The only slightly annoying issue is that when the skin first loads the new profile it will momentarily display the old profile layout until it rebuilds the template.

**Comment by AakashC2020** [comment] 2023-11-20 15:06
> @AakashC2020 - When you get a chance to test, can you let me know if this is still an issue in v0.4 ?
> 
> As far as I can tell from my testing, profile support is working correctly with the new script. The only slightly annoying issue is that when the skin first loads the new profile it will momentarily display the old profile layout until it rebuilds the template.

Hi @jurialmunkey,

All my widget settings and menu items changed to default after today's latest update. I've raised this issue via ticket #219 . Please check and kindly help! I forgot to take a backup recently and don't want to build everything from scratch.

**Comment by AakashC2020** [comment] 2023-11-24 18:34
> @AakashC2020 - When you get a chance to test, can you let me know if this is still an issue in v0.4 ?
> 
> As far as I can tell from my testing, profile support is working correctly with the new script. The only slightly annoying issue is that when the skin first loads the new profile it will momentarily display the old profile layout until it rebuilds the template.

Hi @jurialmunkey,

I think this issue is fixed now. Thank you!

**Closed** 2023-11-25 07:10 UTC
Labels: bug
