### ISSUE TITLE
Search results are difficult to navigate to when using a remote

### ISSUE THREAD

**Issue by Omarscomin** [jurialmunkey/skin.arctic.fuse#622] opened 2024-03-22 15:14 UTC
### Skin section

Widgets

### Current Behavior

It is extremely difficult to get to my search results when using a remote. I can't navigate from the search term _or_ the key pad. I have to scroll down to "Content" first, and from there I can finally scroll to the left and get to the search results. 

### Expected Behavior

To be able to easily and conveniently navigate to search results  

### Steps To Reproduce

1. Search for a movie/show by using the keypad with a remote
2. Try to navigate to your search results 

### Screenshots and Additional Info

https://vimeo.com/926309515

OS: Android
Device: 2019 Nvidia Shield Pro
Kodi version: Omega RC2

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment] 2024-03-22 16:52
I haven't tried the most recent updates yet but up till 0.5.18 I can confirm experiencing this problem as well. Same device, same Kodi version.

I didn't actually figure out a way to navigate to the content. 
After searching, I see results but no selector or menu, arrows also didn't seem to do anything. But it seemed like the menu (or at least the searchbox) was still focused because when I pressed back the search refreshed as if I had deleted one letter of my search. Repeatedly pressing back was the only way to get out of the search screen. Might be something to do with visibility and focus.

**Comment by matthius7** [comment] 2024-03-22 20:22
Same here on Chromecast 4k can barely get out of search box and when I get to result I can't select anything have to force close Kodi to escape search.

**Comment by jurialmunkey** [comment] 2024-03-22 22:15
I cannot override the behaviour of the edit control box. Kodi steals the back button press.

You should be able to press back from any other control in the dialog to return to the search results.

**Comment by Omarscomin** [comment] 2024-03-23 00:37
> I cannot override the behaviour of the edit control box. Kodi steals the back button press.
> 
> You should be able to press back from any other control in the dialog to return to the search results. 

Ah, my apologies. I could've sworn that I tested that and it took me back to the home page, but I was mistaken. It does, in fact, take you to the first search result.

Admittedly, it feels more natural for me to scroll to the left to get to the search results, but I will just adjust to this. Thank you for the quick response.

**Comment by jurialmunkey** [comment] 2024-03-23 01:59
> Admittedly, it feels more natural for me to scroll to the left to get to the search results, but I will just adjust to this. Thank you for the quick response.

Yeah I need to fix this for the letters/edit control. It works for all the other button but letters loop around which is a mistake on my part.

> I could've sworn that I tested that and it took me back to the home page, but I was mistaken. It does, in fact, take you to the first search result.

If there are no results, it will close the window immediately. If there are results, it focuses the item, and then back again closes the window.

I had considered adding a "no results" dummy item so that the back key always goes to the results even if there are none, but it felt like a bit of an unnecessary extra step.

**Comment by Rinicko** [comment] 2024-03-23 02:31
> > Admittedly, it feels more natural for me to scroll to the left to get to the search results, but I will just adjust to this. Thank you for the quick response.
> 
> Yeah I need to fix this for the letters/edit control. It works for all the other button but letters loop around which is a mistake on my part.
> 

I think the letters looping around is a good thing... if they don't loop, users might end up closing the dialog by mistake while trying to get to the end letters.. This could possibly lead to a frustrating experience when using the letters. 

It is better to let them loop and have people either go down to content to exit with left key or just press back when the results come up

**Comment by matthius7** [comment] 2024-03-23 02:39
> > > Admittedly, it feels more natural for me to scroll to the left to get to the search results, but I will just adjust to this. Thank you for the quick response.
> > 
> > 
> > Yeah I need to fix this for the letters/edit control. It works for all the other button but letters loop around which is a mistake on my part.
> 
> I think the letters looping around is a good thing... if they don't loop, users might end up closing the dialog by mistake while trying to get to the end letters.. This could possibly lead to a frustrating experience when using the letters.
> 
> It is better to let them loop and have people either go down to content to exit with left key or just press back when the results come up

I can exit out of the search box by going left but when I get into results using a remote I can't choose anything. Hover over anything nothing.

**Comment by jurialmunkey** [comment] 2024-03-23 04:07
> 
> I can exit out of the search box by going left but when I get into results using a remote I can't choose anything. Hover over anything nothing.

I can't reproduce this issue. Need more details about how to recreate it.

**Closed** 2024-03-23 07:14 UTC
Labels: bug

**Comment by Omarscomin** [comment] 2024-03-23 12:15
> I cannot override the behaviour of the edit control box. Kodi steals the back button press.
> 
> You should be able to press back from any other control in the dialog to return to the search results. 

Ah, my apologies. I could've sworn that I tested that and it took me back to the home page, but I was mistaken. It does, in fact, take you to the first search result.

Admittedly, it feels more natural for me to scroll to the left to get to the search results, but I will just adjust to this. Thank you for the quick response.

@jurialmunkey I can't find the option to search on the most recent update

**Comment by matthius7** [comment] 2024-03-23 12:26
> > I can exit out of the search box by going left but when I get into results using a remote I can't choose anything. Hover over anything nothing.
> 
> I can't reproduce this issue. Need more details about how to recreate it.

I've been looking since I woke up and no longer have a search feature or menu button

**Comment by jurialmunkey** [comment] 2024-03-23 22:23
The top and bottom fixed position icons have been removed. In the default set the top icon in the menu is now search instead of home.

 So if you don't want to reset to defaults then you will need to add the shortcut yourself. You can find it in the hubs shortcuts.

**Comment by matthius7** [comment] 2024-03-24 03:30
> The top and bottom fixed position icons have been removed. In the default set the top icon in the menu is now search instead of home.
> 
> So if you don't want to reset to defaults then you will need to add the shortcut yourself. You can find it in the hubs shortcuts.

Works nicely . Two things I figured out why I was on a dead screen so to speak after finding the results in search. Where I couldn't do anything with results of search.  I had the style set in search on default which is landscape. I changed to poster and it works perfectly now. You can test the theory and see what I was talking about indeed a bug on default view type  in search. And how can I make the menu button that used to be fixed on the bottom ? Not under any hubs or miscellaneous. Great skin btw . You rock my friend.

**Comment by jurialmunkey** [comment] 2024-03-24 09:41
> I changed to poster and it works perfectly now. You can test the theory and see what I was talking about indeed a bug on default view type in search.

Yeah I realised that was the issue, though it should be fixed in 0.6.0 as that's what I did in the commit above: https://github.com/jurialmunkey/skin.arctic.fuse/commit/6cdad89803e3740305a4579c748ae5ab03f883b1
