### ISSUE TITLE
Scroll sections instead pressing select

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#234] opened 2023-11-24 03:38 UTC
### Skin section

Home Widgets

### Feature description

I may have not found how to make this work. When I scroll through sections (as seen in video) I must press enter. Is there a way just to scroll and it opens that section automatically? If not, can I request an option to allow like H2. Thank you!🙏 

### Why is this feature needed? Please justify and explain.

Just makes it faster and not pressing so many times. 

### Screenshots and Additional Info

![1HFVMBPBF_AFMR0C](https://github.com/jurialmunkey/skin.arctic.fuse/assets/63697905/4deb89f9-b5a8-4b7c-936c-b9203ebcd5c4)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2023-11-24 03:42
Duplicate of #235

**Closed by jurialmunkey** 2023-11-24 03:42 UTC
Labels: enhancement
