### ISSUE TITLE
PVR Channel widget thumb suggestions

### ISSUE THREAD

**Issue by ludovik35** [jurialmunkey/skin.arctic.fuse#345] opened 2023-12-22 09:44 UTC
### Skin section

Widgets

### Feature description

Hi @jurialmunkey,

One of best features (for me) in your skin is the PVR support.
I'm big user off this.

After using the PVR Channel widget i'd like to propose some enhancements.
Of course, you take what seems to be insteresting for you.

I hope you'll the quality the quality of the TV show took for the example (Not the best hour to take screenshot)

Here are joined 3 screenshots :

- First : actual design
![PVR Channel widget before-thumb detail](https://github.com/jurialmunkey/skin.arctic.fuse/assets/74715660/c574f6fc-c00c-4fa2-96d3-8ceecb242d2f)

- Second : suggestions of enhancement
![PVR Channel widget after- thumb detail](https://github.com/jurialmunkey/skin.arctic.fuse/assets/74715660/f91978fe-2951-48be-b2ab-4f4f4d5ebf9b)

### Why is this feature needed? Please justify and explain.

To be cleared, here is the explanation of this suggestions :

![PVR Channel widget thumb modifs detail](https://github.com/jurialmunkey/skin.arctic.fuse/assets/74715660/79cf8206-de84-47ac-a555-e0597368b194)
 
1 - Replace actual channel name by epg program title (xmltv title)
2 - Replace actual channel name by epg program subtitle (xmltv subtitle)
3 - Delete actual progress bar
4 - Delete date (PVR widget always show actual programs so the date is not useful) but keep hour
5 - Add a progress symbol like on others widget (i e : in progress TV shows). This could be bigger to include in his middle channel icon

### Screenshots and Additional Info

I also join you a full window screenshot with these suggestions. Only 2 thumbnails have been change whit this design (because it was very long to duplicate) but of course changes are for all thumbnails.

![PVR Channel widget after](https://github.com/jurialmunkey/skin.arctic.fuse/assets/74715660/41f44292-f638-4843-8e25-58e2afab9467)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2023-12-22 10:11
The progress bar is out of necessity. 

To display the circle I need progress as a number which is then joined to a png texture name e.g. 45 is 45.png here:
https://github.com/jurialmunkey/skin.arctic.fuse/tree/omega/media/progress/circle

The issue is that in PVR item, ListItem.Progress doesn't give a number. It's a special info which can only be used in a progress bar control (which must be a straight line). 

It can be hacked to get a number via a variable but it is very inefficient e.g.

```
<value condition="Integer.IsEqual(ListItem.Progress,1)">1.png</value>
<value condition="Integer.IsEqual(ListItem.Progress,2)">2.png</value>
etc.
```

That's also a problem because it only works for the focused item. You then need separate variables for all the different container IDs and ListITem positions, so it becomes many thousands of lines of code.

**Comment by jurialmunkey** [comment] 2023-12-22 10:12
Date is for recordings. It's a little difficult to differentiate PVR item types and I had to cut out some of the label variables so I have to be judicious with what is and isn't included.

The channel label / sublabel needs to be fixed though.

**Comment by ludovik35** [comment] 2023-12-22 17:00
Thanks for your quick reply.
I understand that it will be very complicated to change the progress bar for a less-than-optimal result.

Don't worry, it was simply to standardize with your other widgets. 

As for the other suggestions, I'd only understood that the formatting was common to all PVR widgets. The date should therefore be retained. Under these conditions, it seems complicated to me to add both titles and subtitles.

But would it be possible to add the channel icon?

Thanks

**Comment by jurialmunkey** [comment] 2023-12-23 03:35
> The date should therefore be retained.

This has been addressed in the above commits. 

I'm now checking if item is currently inprogress. If it is currently in progress (either live tv or live recording) then the bottom right label will show `starttime - endtime`. But if the item has already completed or is in the future, it will show `date time`. 

I think that makes the most sense.

> But would it be possible to add the channel icon?

I'll think about it but generally I find channel icons are too inconsistent.

Some might be square, others will be landscape, and some might have transparent background whilst others have solid ones.

**Comment by ludovik35** [comment] 2023-12-23 14:11
Hello @jurialmunkey,

Thank you for your quick PVR widget update. I'm on the road for vacation 🎅. 
So I'll have to wait until I get back to test it.

You're right about the channel icons. There's no standardization of them which complicates the skinner's task. 

I've got a few ideas on the subject. 
If you agree, I can open a discussion (probably not before I get back) to give us time to think.

If that's okay with you, you can close this issue.

**Comment by jurialmunkey** [comment] 2023-12-23 23:12
Not a problem at all! Yes when you get back, feel free to open up a discussion. Enjoy your trip!

**Closed by jurialmunkey** 2023-12-23 23:12 UTC
Labels: enhancement
