### ISSUE TITLE
Remove Spotlight on Complex mode.

### ISSUE THREAD

**Issue by suenabien84** [jurialmunkey/skin.arctic.fuse#748] opened 2024-04-19 11:23 UTC
### Skin section

Widgets

### Feature description

Spotlight on complex mode [enable/disable] function.

### Why is this feature needed? Please justify and explain.

I love the complex mode for the use of sidemenu>categories>widgets but the Spotlight is occupying an area on the screen so I can't have everything without "scrolling" down.

I would like to have sidemenus as hubs, so for example I chose the sidemenu "Movies" and on the left I'll have categories like "Recommended", "Genres", Years", "Providers"... each of these categories would have their submenus, and each submenu will be widgets, i.e. Movies>Genres>Comedy> Trending Comedy Movies (widget)

### Screenshots and Additional Info

<img width="1440" alt="How I have it" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/78933622/3b4a1330-2566-4f7d-887a-3a1a30d072fa">

<img width="1150" alt="How I want it" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/78933622/8af244e2-59ab-4169-aacd-c95a6fbf8f1c">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Bindou01** [comment] 2024-04-19 21:19
I'm also really looking forward to this option. But unless I'm mistaken, this has already been asked here :
https://github.com/jurialmunkey/skin.arctic.fuse/issues/689

**Comment by jurialmunkey** [comment] 2024-04-19 21:33
Yep this one is duplicate of #689

**Closed by jurialmunkey** 2024-04-19 21:33 UTC
Labels: enhancement
