### ISSUE TITLE
losing focus when moving to first item upon startup

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#649] opened 2024-03-26 21:47 UTC
### Skin section

Widgets

### Current Behavior

upon startup, using classic mode, focus is on second menu item [tv shows] and if I press right, focus will not go to first item of first widget, it will get lost. If I go back to first menu item [movies] this is working properly. I have move between widgets groups disabled. I will need to reload skin for it to work properly on tv shows. This is happening on start up only.

### Expected Behavior

once right button is pressed upon startup, focus should be on the first item of the first widget.

### Steps To Reproduce

boot kodi
wait for widgets to load
by this stage you should be on second menu item
press right arrow/button
focus is lost

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment] 2024-03-26 23:06
Can confirm I have this too.

**Comment by jurialmunkey** [comment] 2024-03-26 23:16
I can't reproduce this issue. I use Classic mode on my loungeroom setup.

Is this Omega or Nexus? Any other info about how to reproduce?

Also what happens if you go into widget customisation for side menu and change which item has default focus? Does it still happen if you set first item to default focus? (note that if the setting hasn't ever been changed it will incorrectly show the first item as default when it should actually be second -- this is just a visual error which can be resolved by toggling the button on/off and is fixed in next version).

**Comment by jurialmunkey** [comment] 2024-03-26 23:24
Actually scrap that, I think I managed to create a scenario where it happens. Fix incoming.

**Closed** 2024-03-26 23:29 UTC
Labels: bug

**Comment by jurialmunkey** [comment] 2024-03-26 23:33
^^^ That should fix it. You might need to tap right twice initially from startup (first move will only refocus the menu properly and then second to move to widget) but focus shouldn't get stuck. 

It will only be after initial startup that tapping twice will be needed and should work properly with a single press from there on.

**Comment by vella9** [comment] 2024-03-27 05:22
great! thank you as always for your work!

**Comment by vella9** [comment] 2024-03-27 20:42
Hi @jurialmunkey , sorry to bother you again, but this issue resurfaced. 

This time however it occurred once I returned to the main screen after I was watching an episode. The continue watching widget got updated, I went to the side menu item and hovered over the first side menu item [Movies] and when I pressed right to focus on the first item on the widget, the same issue reoccurred.
