### ISSUE TITLE
spotlight items show studio logo in bottomright

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#683] opened 2024-04-04 11:18 UTC
### Skin section

Widgets

### Current Behavior

Spotlight items show studio logo in bottomright corner of screen, overlapping the widget there.

### Expected Behavior

Do not show studio logo of spotlight items, or place it somewhere else where it is not overlapping the widgets.

### Steps To Reproduce

1. Go to a page with spotlight.
2. Notice the studio logo in the bottomright corner of the screen.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment] 2024-04-04 20:26
This is a duplicate of #659. 
And I believe that one was closed by increasing widget fadeout when spotlight is in focus.

**Comment by xyzfre** [comment] 2024-04-04 20:55
I believe the same and now with the fade out it actually looks pretty good.

**Comment by Aemstel2** [comment] 2024-04-04 20:56
I don't know. Still happening here with latest version.

**Comment by jurialmunkey** [comment] 2024-04-04 22:13
> I don't know. Still happening here with latest version.

Screenshot?

Widget at bottom should fade out to 30%

**Comment by Aemstel2** [comment] 2024-04-04 22:24
![shot](https://github.com/jurialmunkey/skin.arctic.fuse/assets/109811164/96e2d579-e702-4134-a1ce-46abfa4a7ffa)

**Comment by jurialmunkey** [comment] 2024-04-04 22:29
That's working correctly as intended.

Bottom right is always visible. This is particular important if clock or now playing is displayed.

The widget in the lower position is faded out to 30% to compensate.

**Comment by Aemstel2** [comment] 2024-04-04 22:38
Ok, I understand in that case why bottom right is always visible. But in my case, it looks weird to me; spotlight - horizontal menu - widgets, and then that logo there. Even with the widget faded.

**Comment by jurialmunkey** [comment] 2024-04-04 22:46
You could change spotlight style to fanart so that it pushes down when focused.

I'm not sure what other solution there is. Hiding the widget completely would be very strange. My only options are to either push every thing further down or just the widgets. But both those have downsides.

Pushing down the widgets only leaves a big gap from categories and is a problem for the slide up categories on focus option.

Pushing all the content down a bit breaks the consistent position of the info panel.

**Comment by Aemstel2** [comment] 2024-04-04 23:26
To me it seems like the spotlight section should end at the horizontal menu. So it's strange for a logo being way down there. I would get rid of the logo there, if at all possible. But maybe I am misunderstanding the intended look of it all?

**Comment by jurialmunkey** [comment] 2024-04-05 01:15
>  I tried fanart spotlight, and can see what you mean. I don't much like that option. I also feel the studio logo showing in widgets at bottom right is not very nice. I think an option to get rid of that bottomright content on home pages would be nice, if possible.

There's already an option to disable logos in the bottom right.

It needs to be either on or off. Way too many micro settings. Makes things incredibly difficult to manage and the skin slower because it needs to evaluate way more conditions. 

As an example, this is how unweildy it makes the code:

As it is currently with one global setting:
`Skin.HasSetting(Furniture.BottomRight.Disable)`

vs 

What you are requesting
`[[Skin.HasSetting(Furniture.BottomRight.Disable) + ![Window.IsVisible(Home) | Window.ISVisible(1101) | Window.ISVisible(1102) | Window.ISVisible(1103) | Window.ISVisible(1104) | Window.ISVisible(1105) | Window.ISVisible(1106) | Window.ISVisible(1107) | Window.ISVisible(1108) | Window.ISVisible(1109)]] | [Skin.HasSetting(Furniture.Hubs.BottomRight.Disable) + [Window.IsVisible(Home) | Window.ISVisible(1101) | Window.ISVisible(1102) | Window.ISVisible(1103) | Window.ISVisible(1104) | Window.ISVisible(1105) | Window.ISVisible(1106) | Window.ISVisible(1107) | Window.ISVisible(1108) | Window.ISVisible(1109)]]`

And that's only two simple settings -- one for Home/Hubs and one for everywhere else. It gets worse once you add more complex scenarios in.

**Comment by Aemstel2** [comment] 2024-04-05 14:16
I understand. Just leave it as is, I would say. It's no big deal. It's still the greatest skin there is :)

Also the fade is nice!

**Closed** 2024-04-06 06:41 UTC
Labels: bug

**Comment by xyzfre** [comment] 2024-04-07 21:26
Looks perfect👌🏼 now @jurialmunkey
