### ISSUE TITLE
:bug: Skin elements missing after opening several windows

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#294] opened 2023-12-13 17:02 UTC
### Skin section

Widgets

### Current Behavior

Hi
Let see if I can explain this.
First this only happens if I setup music hub. If I do not configure music hub everything works ok.
If I configure music hub with my library after a while of browsing through the different menus/categories some of them loose elements/information as you can see on the pictures attached.
This happens since early stages of the skin but only now I find that is the music hub that is the problem.
Strange that nobody seems to report a problem like this.
I use emby for kodi to populate my libraries on kodi. It’s large libraries but I think that is not problem, because without the music hub everything works ok.
Sorry my English. 

PS: if I click reload it works ok but after a while it happens again.
if you need I can make a video. 

### Expected Behavior

Well , everything works ok 😀

### Steps To Reproduce

Configure music hub with a music library
Browse through music library and then go back and browse for a while on different menus.
After a while when we select movies or tv shows or settings widget, some elements/text disappear.

### Screenshots and Additional Info

![IMG_5763](https://github.com/jurialmunkey/skin.arctic.fuse/assets/51266902/fc21d99e-5a00-4590-aa95-fc1548e13c21)
![IMG_5760](https://github.com/jurialmunkey/skin.arctic.fuse/assets/51266902/879f2c31-499c-46ec-b4b7-3399af02b36c)
![IMG_5761](https://github.com/jurialmunkey/skin.arctic.fuse/assets/51266902/7a957667-eb02-4af9-b3ff-f7c802e59baa)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2023-12-13 21:59
Okay it's not just me then!

Can confirm that I've seen this before but certain as to the cause.

As far as I can tell, I'm hitting some unexpected upper limit on the number of skin `$VAR[]` variables and `$EXP[]` expressions that Kodi can evaluate. Once the limit hits weird rendering behaviour happens.

I don't think its any specific window. It just happens more often to music because that's usually opened after videos. If you restart Kodi and then open music first it will be fine and you probably can get it to happen in videos instead.

Still trying to figure out exactly what it is so that I can make a test case in Estuary to report the bug, but it definitely seems to be related to number of $VAR that Kodi has evaluated. 

If you disable the wall view (which has a lot of variables) then it seems to bring it under the limit. The wall isn't the cause but its an easy part of the skin to disable to bring the number of $VAR and $EXP in use down considerably.

**Comment by rapteev** [comment] 2023-12-13 22:15
You are right. I already noticed this several times before. Now I remember that it also happens one time even before I setup music library. 
Some time ago I did that. Disabled wall view but if I remember even with wall view disabled after some time it happens.
Really hope you can fix it. Reloading skin fix it temporary but it keep happening.

**Comment by jurialmunkey** [comment] 2023-12-13 22:18
In screenshot below I managed to trigger it in MyVideoNav, so not related to any specific window. As far as I can tell it's just the order opened.

Definitely seems to be `$VAR[]` related. In my second screenshot below I replaced the plotbox variable with a static info label `$INFO[ListItem.Plot]` as a quick test of my hypothesis and the plot displayed correctly. 

This is something that will need to be fixed in Kodi as the skin isn't doing anything wrong -- there just seems to be some unintended upper limit on the number of variables Kodi can evaluate. It'd be a memory management issue of some kind.

![screenshot00265](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/8b1922c0-39ae-4774-a2d8-1c89d6344ac6)

![screenshot00266](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/dbd01baa-48d2-4566-830e-70bca0047b76)

**Comment by rapteev** [comment] 2023-12-13 22:25
Well, if it’s kodi probably it can be fixed before v21 enters final releases.

**Comment by jurialmunkey** [comment] 2023-12-13 23:02
> Well, if it’s kodi probably it can be fixed before v21 enters final releases.

If I can't make a reproducible test case in Estuary then that is very unlikely to happen.

**Comment by jurialmunkey** [comment] 2023-12-14 01:02
^^^ These commits should at least reduce number of variables enough to avoid the issue triggering for now.

**Comment by rapteev** [comment] 2023-12-14 09:28
Thank you very much Jurialmunkey.
I will try it and report back.

**Comment by rapteev** [comment] 2023-12-14 12:15
Hi Jurialmunkey 
Concerning this problem it seems to be working ok on latest nightly omega. I tried browsing all menus, submenus, go to settings (change some widgets), go back and repeat the process, play movie, play tvshows, play music and tv. Repeat the process 3/4 times. Before it will happen long before all this, so I’d say it seems ok now. I will do further testing and report back.

Now the bad news  🙂 (well not so bad, just a little bug I find doing all this)
On music artists if we select an artist information we are presented with a window for that artist with 4 options, browse, albums, YouTube and wiki. Everything seems to work ok except for albums. On that window if you select an album nothing happens (I think that it should open new window with the songs for that album, right?)

Thank you again and keep the fantastic work on this great skin.

**Comment by rapteev** [comment] 2023-12-14 23:25
> I think this commit might have introduced a new bug for various Next Episodes/Up Next lists which are "TV Show" lists, but for the next available episode of each TV show. It seems that none of the indicators appear on these list items anymore.

Hi
I didn’t notice that ( I’m just happy that I can enjoy the skin without half of it suddenly disappear 🫠) , but I will try to see if is happening to me.

**Comment by jurialmunkey** [comment] 2023-12-14 23:36
> I think this commit might have introduced a new bug for various Next Episodes/Up Next lists which are "TV Show" lists, but for the next available episode of each TV show. It seems that none of the indicators appear on these list items anymore.

Yeah I only tested with the library where the IsResumable flag gets set for TV Shows with unwatched episodes. Forgot that this doesn't happen in some plugins.

**Comment by rapteev** [comment] 2023-12-15 12:15
Hi Jurialmunkey 

Just a follow up. Yesterday I used it for about 6/7 hours and everything goes ok. It didn’t happen a single time ( I only have one problem that kodi became unresponsive, but I don’t think that was skin related, more probably kodi itself or Spotify plugin not being 100% compatible with Omega. It happens right after I used this plugin).
So I have to say thank you one more time. 
I’ll keep looking for any problem.

**Comment by jurialmunkey** [comment] 2023-12-16 00:18
@rapteev - Thanks heaps for testing and confirming. I'll close this as complete for now. 

Hopefully I can figure out a way to reproduce it in Estuary to make a test case for a bug report and get the underlying issue fixed in Kodi's skinning engine -- but at least now the skin will not trigger the bug to happen!

**Closed by jurialmunkey** 2023-12-16 00:18 UTC
Labels: bug
