### ISSUE TITLE
:bug: Trailer does not play in the background

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#645] opened 2024-03-26 12:35 UTC
### Skin section

Widgets

### Current Behavior

The background video option is activated but when I click on the trailer it opens in the dialog

### Expected Behavior

.

### Steps To Reproduce

.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment] 2024-03-26 13:44
This is not a bug, but a new update.

**Comment by xyzfre** [comment] 2024-03-26 15:38
@adamosborne83 I haven't got a chance to try the new update, so there's no more full screen trailers.

**Comment by adamosborne83** [comment] 2024-03-26 15:39
> @adamosborne83 I haven't got a chance to try the new update, so there's no more full screen trailers.

https://github.com/jurialmunkey/skin.arctic.fuse/issues/630

Here buddy.

**Comment by jurialmunkey** [comment] 2024-03-26 23:12
Behaviour has been standardised. 

Trailer side *buttons* such as in info or context menu will always open the trailer dialog. From there, there is a button to switch to a fullscreen view.

Additionally, there is now an option to start trailers playing automatically when info dialog is opened. Automatically playing trailers will start in the background and will automatically stop when closing the info dialog.

`Skin Settings > Behaviour > Trailers > Play trailers automatically (background)`

**Closed by jurialmunkey** 2024-03-26 23:12 UTC
Labels: bug

**Comment by Liquidrag** [comment] 2024-03-27 14:39
> Behaviour has been standardised.
> 
> Trailer side _buttons_ such as in info or context menu will always open the trailer dialog. From there, there is a button to switch to a fullscreen view.
> 
> Additionally, there is now an option to start trailers playing automatically when info dialog is opened. Automatically playing trailers will start in the background and will automatically stop when closing the info dialog.
> 
> `Skin Settings > Behaviour > Trailers > Play trailers automatically (background)`

Love the new setup! I've switched to background now that autoplay in info has been implemented.
