### ISSUE TITLE
[Feature] clock at the top of the screen

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/skin.arctic.fuse#89] opened 2023-08-07 14:08 UTC
### Skin section

Fullscreen Video OSD

### Feature description

Added a clock at the top of the screen
in huge font

### Why is this feature needed? Please justify and explain.

Today it is in the lower part and it is small and indistinct

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/3d1f1b04-44c7-4abb-beae-66d2d5538e58)
What it should look like

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2023-08-07 14:15
Duplicate of #9

**Closed by jurialmunkey** 2023-08-07 14:15 UTC
Labels: enhancement

**Comment by test01203** [comment] 2023-08-07 14:21
> Duplicate of #9

I didn't talk about it here, I wrote that it is inside the movie itself in the OSD

**Comment by jurialmunkey** [comment] 2023-08-07 14:49
This is the same issue because the header is displayed in both places. Changing the header in one place will affect the other.
