### ISSUE TITLE
Option to disable the text that is displayed while content is loading

### ISSUE THREAD

**Issue by Omarscomin** [jurialmunkey/skin.arctic.fuse#660] opened 2024-03-29 16:33 UTC
### Skin section

Widgets

### Feature description

I was wondering if it would be possible to add the option to disable the text that is displayed while widgets are loading (see picture below)

### Why is this feature needed? Please justify and explain.

I don't like being reminded of how much time I spend watching TV😂

It would also look a little cleaner, in my opinion, with the recent category visibility options. 

### Screenshots and Additional Info

![Kodi_20240328_073900](https://github.com/jurialmunkey/skin.arctic.fuse/assets/129215684/8922022c-0e87-4695-969b-bb7bced7d477)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment] 2024-03-29 20:47
Ooooooo she didnttttttt

**Comment by jurialmunkey** [comment] 2024-03-29 22:07
Duplicate of #226

**Closed by jurialmunkey** 2024-03-29 22:07 UTC
Labels: enhancement
