### ISSUE TITLE
:sparkles: Option to disable displayed content data

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#667] opened 2024-03-31 22:22 UTC
### Skin section

Widgets

### Feature description

Could there be an option to deactivate this data from the displayed content?

### Why is this feature needed? Please justify and explain.

This data does not need to appear for many people like me, it would be nice to have the option to disable it

### Screenshots and Additional Info

![IMG_20240401_002229](https://github.com/jurialmunkey/skin.arctic.fuse/assets/159583868/eb2b6f56-f2f6-43e3-944e-f14479b170e4)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by CyberRooke** [comment] 2024-03-31 22:29
https://github.com/jurialmunkey/skin.arctic.fuse/issues/226

**Comment by jurialmunkey** [comment] 2024-04-01 02:09
Duplicate of #226

**Closed by jurialmunkey** 2024-04-01 02:09 UTC
Labels: enhancement
