### ISSUE TITLE
Option to hide spotlight view

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#700] opened 2024-04-07 23:04 UTC
### Skin section

Spotlight/Widgets

### Feature description

Hi Jurial, can you suggest the possibility of removing or hide the Spotlight view (A more focused view on the category list) ? This would be nice because here we don't use it at all, and it ultimately clutters the interface, very often requiring us to go through the "Read" button in the Spotlight before reaching the side shortcuts of the other hubs. And I think we are not the only ones. I don't know if this is a lot of work, if it is, forget it.

### Why is this feature needed? Please justify and explain.

This would provide better usability for those who primarily use the horizontal categories to view movies, and don't use the Sportlight view.

Thank you again very much for everything you do.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment] 2024-04-07 23:44
Duplicate of #689

**Closed by jurialmunkey** 2024-04-07 23:44 UTC
Labels: enhancement
